# Generated by Django 5.0.2 on 2024-03-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
