# Generated by Django 5.0.2 on 2024-03-31 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('repeat_password', models.CharField(max_length=100, verbose_name='Repeat Password')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('repeat_email', models.EmailField(max_length=254, verbose_name='Repeat Email')),
                ('send_test_account_settings', models.BooleanField(default=True, verbose_name='Send me test account settings')),
                ('subscribe_to_newsletter', models.BooleanField(default=True, verbose_name='Subscribe to monthly newsletter')),
                ('accept_terms_of_service', models.BooleanField(default=False, verbose_name='Accept terms of service')),
            ],
        ),
    ]
