# Generated by Django 5.0.2 on 2024-05-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_user_password_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1234567890, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
